# @package _global_
name: "crossmodal"
algebra:
  p: 6
  q: 0
  device: "cpu"
dataset:
  name: "20newsgroups"
  embedding_dim: 6
  max_samples: null
  cache_dir: "./data/newsgroups"
model:
  in_channels: 8
  hidden_channels: 16
training:
  epochs: 200
  lr: 0.01
  batch_size: 64
  seed: 42
