# @package _global_
name: "feynman"

algebra:
  p: 4
  q: 0
  device: "auto"

dataset:
  name: "feynman"
  equation: "I.6.20"
  n_samples: 10000
  noise: 0.0
  cache_dir: "./data/feynman"

model:
  hidden_channels: 16
  num_layers: 3
  num_rotors: 8
  embed_grade2: false
  use_decomposition: false

training:
  epochs: 100
  lr: 0.001
  batch_size: 128
  optimizer_type: "riemannian_adam"
  max_bivector_norm: 10.0
  sparsity_weight: 0.01

orthogonality:
  enabled: false
  mode: "loss"
  weight: 0.05
  target_grades: null
  monitor_interval: 10
  coupling_warn_threshold: 0.3
  warmup_epochs: 10
