# @package _global_
name: "feynman"

algebra:
  p: 4
  q: 0
  device: "cpu"

dataset:
  name: "feynman"
  equation: "I.6.20"        # Default: Gaussian equation (3 vars)
  n_samples: 10000
  noise: 0.0                 # Gaussian noise std fraction (0 = noiseless)
  cache_dir: "./data/feynman"

model:
  hidden_channels: 16
  num_layers: 3
  num_rotors: 8
  embed_grade2: false        # Enable grade-2 pairwise embedding
  use_decomposition: false   # Bivector decomposition in rotors

training:
  epochs: 100
  lr: 0.001
  batch_size: 64
  optimizer_type: "riemannian_adam"
  max_bivector_norm: 10.0
  sparsity_weight: 0.01      # Weight for rotor L1 sparsity loss

orthogonality:
  enabled: false             # true to activate grade-orthogonality enforcement
  mode: "loss"               # "loss" = soft penalty | "project" = hard zero-out
  weight: 0.05
  target_grades: null        # null = all grades | e.g. [0,1,2] for scalar+vector+bivector
  monitor_interval: 10       # print ASCII diagnostics every N epochs
  coupling_warn_threshold: 0.3
  warmup_epochs: 10          # linear ramp from 0 -> weight over this many epochs
