# @package _global_
name: "md17"
algebra:
  p: 3
  q: 0
  device: "auto"
dataset:
  name: "md17"
  molecule: "aspirin"
  samples: 50000
model:
  hidden_dim: 32
  layers: 4
  num_rotors: 12
  max_z: 100
  use_decomposition: true
  decomp_k: 10
  use_rotor_backend: true
training:
  epochs: 100
  lr: 0.001
  batch_size: 64
  optimizer_type: "riemannian_adam"
  loss_weights:
    energy: 1.0
    force: 10.0
    sparsity: 0.01
    conservative: 0.1
    grade_reg: 0.01
  target_spectrum: [0.4, 0.4, 0.15, 0.05]
  max_bivector_norm: 10.0
