# @package _global_
name: "multi_rotor_qm9"
algebra:
  p: 3
  q: 0
  device: "cpu"
dataset:
  name: "qm9"
  samples: null
  target: "U0"
model:
  hidden_dim: 16
  layers: 4
  num_rotors: 12
training:
  epochs: 500
  lr: 0.001  # Adjusted for Riemannian optimization
  batch_size: 2048
