# @package _global_
name: "semantic"
algebra:
  p: 6
  q: 0
  device: "cpu"
dataset:
  name: "20newsgroups"
  embedding_dim: 6
  max_samples: null
  cache_dir: "./data/newsgroups"
model:
  in_channels: 8
  hidden_dim: 16
training:
  epochs: 10
  lr: 0.001  # Adjusted for Riemannian optimization
  batch_size: 64
  seed: 42
