# @package _global_
name: "weatherbench"
algebra:
  p: 2
  q: 1                          # Spacetime signature Cl(2,1)
  device: "auto"
dataset:
  name: "weatherbench"
  resolution: "5.625deg"
  variables: ['z500', 't850']
  lead_time: 72
model:
  spatial_hidden_dim: 64
  num_spatial_layers: 6
  num_temporal_steps: 12
  num_rotors: 16
  use_decomposition: true
  decomp_k: 10
  use_rotor_backend: true
training:
  epochs: 50
  lr: 0.001
  batch_size: 8
  optimizer_type: "riemannian_adam"
  max_bivector_norm: 10.0
  physics_weight: 0.1
  loss_weights:
    forecast: 1.0
    sparsity: 0.01
    grade_reg: 0.01
  target_spectrum: [0.15, 0.35, 0.35, 0.15]
